spring:
  profiles:
    active: local
  main:
    log-startup-info: false
  jackson:
    serialization:
      indent-output: true
    time-zone:
      Asia/Ho_Chi_Minh  
---
spring:
  profiles: local
  datasource:
    url: jdbc:mysql://localhost:3306/vti_academy
    username: root
    password: north
    driverClassName: com.mysql.cj.jdbc.Driver
    hikari:
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        
  mail:
    host: smtp.googlemail.com
    password: vietanh99
    port: 25
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
    username: menbinh74@gmail.com
    default-encoding: UTF-8

     
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    database: MYSQL
    show-sql: true
    open-in-view: false
    properties:
      hibernate.id.new_generator_mappings: true
      hibernate.cache.use_second_level_cache: true
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: true
      hibernate.cache.region.factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
      javax.persistence.sharedCache.mode: ENABLE_SELECTIVE
    hibernate:
      ddl-auto: none
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
  http:
    multipart:
      max-file-size: 300MB
      max-request-size: 300MB
server:
  context-path: /VTI_Academy_Web
  port: 8080
security:
  basic:
    enabled: false
---
spring:
  profiles: product
  datasource:
    url: jdbc:mysql://localhost:3306/vti_academy?useSSL=false
    username: ubuntu
    password: VTI@12345Ab
    driverClassName: com.mysql.cj.jdbc.Driver
    hikari:
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
  
  mail:
    host: smtp.googlemail.com
    password: 140699Quang699
    port: 25
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
    username: leechongque@gmail.com
    default-encoding: UTF-8      
     
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    database: MYSQL
    show-sql: false
    open-in-view: false
    properties:
      hibernate.id.new_generator_mappings: true
      hibernate.cache.use_second_level_cache: true
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: true
      hibernate.cache.region.factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
      javax.persistence.sharedCache.mode: ENABLE_SELECTIVE
    hibernate:
      ddl-auto: none
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
  http:
    multipart:
      max-file-size: 300MB
      max-request-size: 300MB
server:
  context-path: /VTI_Academy_Web
  port: 8082
security:
  basic:
    enabled: false